#!/bin/sh
set -eu

repository_root=$(git rev-parse --show-toplevel)
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY
unset GIT_ALTERNATE_OBJECT_DIRECTORIES GIT_COMMON_DIR GIT_PREFIX
unset GIT_INTERNAL_SUPER_PREFIX GIT_SHALLOW_FILE
exec "$repository_root/scripts/check.sh"
