[webrtc]
enabled = true
video_only = true
signaling_loopback = true
udp_port = 8443
http_port = 8554
max_clients = 1
cert = /etc/ssl/certs/uhttpd.crt
key = /etc/ssl/private/uhttpd.key
https = false

[log]
level = info
target = syslog
