[audio]
enabled = true
ai_enabled = false
ao_enabled = false
input = amic
device = 1
codec = l16
sample_rate = 16000
volume = 60
gain = 10
ao_sample_rate = 16000
ao_volume = 40
ao_gain = 0
aec_enabled = false
ns_enabled = false
hpf_enabled = false
agc_enabled = false

[privacy]
enabled = false
