"""Register the guided stock-recovery command family."""

from __future__ import annotations


def register_stock_recovery_commands(facade: object, commands: object) -> None:
    Path = getattr(facade, "Path")
    _add_common = getattr(facade, "_add_common")
    backup_capture_handler = getattr(facade, "_stock_backup_capture")
    backup_prepare_handler = getattr(facade, "_stock_backup_prepare")
    backup_validate_handler = getattr(facade, "_stock_backup_validate")
    uartless_authorize_handler = getattr(facade, "_stock_uartless_authorize")
    uartless_handoff_handler = getattr(facade, "_stock_uartless_handoff")
    uartless_prepare_handler = getattr(facade, "_stock_uartless_prepare")
    uartless_validate_handler = getattr(facade, "_stock_uartless_validate")
    live_authorize_handler = getattr(facade, "_stock_live_authorize")
    live_prepare_handler = getattr(facade, "_stock_live_prepare")
    live_restore_handler = getattr(facade, "_stock_live_restore")
    live_passivate_handler = getattr(facade, "_stock_live_passivate")
    sd_authorize_handler = getattr(facade, "_stock_sd_authorize")
    sd_confirmation_handler = getattr(facade, "_stock_sd_confirmation")
    sd_handoff_handler = getattr(facade, "_stock_sd_handoff")
    sd_passivate_handler = getattr(facade, "_stock_sd_passivate")
    sd_prepare_handler = getattr(facade, "_stock_sd_prepare")
    sd_retry_handler = getattr(facade, "_stock_sd_retry")
    restore_inspect_handler = getattr(facade, "_stock_restore_inspect")
    restore_prepare_handler = getattr(facade, "_stock_restore_prepare")

    stock = commands.add_parser("stock-recovery", help="capture, validate or restore same-camera stock recovery",
        description="Choose recovery before installing. backup-* preserves an exact-original backup through UART-assisted capture. uartless-* replaces stock mtd1/mtd2 before functional capture and cannot claim exact-original recovery. restore-*, live-* and sd-* require validated same-camera evidence and their exact confirmations. Prepare writes host/SD artifacts; authorize arms the named physical write. Never infer physical completion from project status.")
    stock_commands = stock.add_subparsers(dest="stock_command", required=True)

    backup_prepare = stock_commands.add_parser("backup-prepare")
    _add_common(backup_prepare, inherited=True)
    backup_prepare.add_argument("--kernel", type=Path, required=True)
    backup_prepare.add_argument("--linux-config", type=Path, required=True)
    backup_prepare.add_argument("--mmc-module", type=Path, required=True)
    backup_prepare.add_argument("--output-dir", type=Path, required=True)
    backup_prepare.add_argument("--mount-root", type=Path, required=True)
    backup_prepare.add_argument("--media-preflight", type=Path, required=True)
    backup_prepare.add_argument("--confirm-physical-device", required=True)
    backup_prepare.add_argument("--clang", type=Path)
    backup_prepare.add_argument("--lld", type=Path)
    backup_prepare.add_argument("--mksquashfs", type=Path)
    backup_prepare.add_argument("--unsquashfs", type=Path)
    backup_prepare.set_defaults(handler=backup_prepare_handler)

    backup_capture = stock_commands.add_parser("backup-capture")
    _add_common(backup_capture, inherited=True)
    backup_capture.add_argument("--input-dir", type=Path, required=True)
    backup_capture.add_argument("--linux-config", type=Path, required=True)
    backup_capture.add_argument("--serial-device", required=True)
    backup_capture.add_argument("--confirm-serial-device", required=True)
    backup_capture.set_defaults(handler=backup_capture_handler)

    backup_validate = stock_commands.add_parser("backup-validate")
    _add_common(backup_validate, inherited=True)
    backup_source = backup_validate.add_mutually_exclusive_group(required=True)
    backup_source.add_argument("--recovery-dir", type=Path)
    backup_source.add_argument("--collector-dir", type=Path)
    backup_validate.add_argument("--output-dir", type=Path)
    backup_validate.add_argument("--confirm-output-dir", type=Path)
    backup_validate.set_defaults(handler=backup_validate_handler)

    uartless_prepare = stock_commands.add_parser("uartless-prepare")
    _add_common(uartless_prepare, inherited=True)
    uartless_prepare.add_argument("--package", type=Path, required=True)
    uartless_prepare.add_argument("--package-manifest", type=Path, required=True)
    uartless_prepare.add_argument("--mount-root", type=Path, required=True)
    uartless_prepare.add_argument("--media-preflight", type=Path, required=True)
    uartless_prepare.add_argument("--confirm-physical-device", required=True)
    uartless_prepare.set_defaults(handler=uartless_prepare_handler)

    uartless_reuse = stock_commands.add_parser("uartless-reuse")
    _add_common(uartless_reuse, inherited=True)
    uartless_reuse.add_argument("--mount-root", type=Path)
    uartless_reuse.add_argument("--output-dir", type=Path, required=True)
    uartless_reuse.add_argument("--confirm-output-dir", type=Path)
    uartless_reuse.add_argument("--confirm-physical-device")
    uartless_reuse.add_argument("--resume", action="store_true",
                                help="explicitly resume removal using the original verified private archive")
    uartless_reuse.set_defaults(handler=getattr(facade, "_stock_uartless_reuse"))

    uartless_authorize = stock_commands.add_parser("uartless-authorize")
    _add_common(uartless_authorize, inherited=True)
    uartless_authorize.add_argument("--package", type=Path, required=True)
    uartless_authorize.add_argument("--package-manifest", type=Path, required=True)
    uartless_authorize.add_argument("--mount-root", type=Path, required=True)
    uartless_authorize.add_argument("--media-preflight", type=Path, required=True)
    uartless_authorize.add_argument("--confirm-physical-device", required=True)
    uartless_authorize.add_argument("--confirm-write-set", required=True)
    uartless_authorize.set_defaults(handler=uartless_authorize_handler)

    uartless_handoff = stock_commands.add_parser("uartless-handoff")
    _add_common(uartless_handoff, inherited=True)
    uartless_handoff.add_argument("--package", type=Path, required=True)
    uartless_handoff.add_argument("--package-manifest", type=Path, required=True)
    uartless_handoff.add_argument("--mount-root", type=Path, required=True)
    uartless_handoff.add_argument("--media-preflight", type=Path, required=True)
    uartless_handoff.add_argument("--confirm-physical-device", required=True)
    uartless_handoff.add_argument("--confirm-stock-uboot-result", required=True)
    uartless_handoff.set_defaults(handler=uartless_handoff_handler)

    uartless_validate = stock_commands.add_parser("uartless-validate")
    _add_common(uartless_validate, inherited=True)
    uartless_validate.add_argument("--collector-dir", type=Path, required=True)
    uartless_validate.add_argument("--package", type=Path, required=True)
    uartless_validate.add_argument("--output-dir", type=Path, required=True)
    uartless_validate.add_argument("--confirm-output-dir", type=Path, required=True)
    uartless_validate.set_defaults(handler=uartless_validate_handler)

    restore_prepare = stock_commands.add_parser("restore-prepare")
    _add_common(restore_prepare, inherited=True)
    restore_prepare.add_argument("--recovery-dir", type=Path, required=True)
    restore_prepare.add_argument(
        "--preserved-readback-dir", type=Path, required=True
    )
    restore_prepare.add_argument("--output-dir", type=Path, required=True)
    restore_prepare.set_defaults(handler=restore_prepare_handler)

    restore_inspect = stock_commands.add_parser("restore-inspect")
    _add_common(restore_inspect, inherited=True)
    restore_inspect.add_argument("--recovery-dir", type=Path, required=True)
    restore_inspect.add_argument(
        "--preserved-readback-dir", type=Path, required=True
    )
    restore_inspect.add_argument("--output-dir", type=Path, required=True)
    restore_inspect.set_defaults(handler=restore_inspect_handler)

    live_prepare = stock_commands.add_parser("live-prepare")
    _add_common(live_prepare, inherited=True)
    live_prepare.add_argument("--recovery-dir", type=Path, required=True)
    live_prepare.add_argument(
        "--preserved-readback-dir", type=Path, required=True
    )
    live_prepare.add_argument("--restore-output-dir", type=Path, required=True)
    live_prepare.add_argument("--kernel", type=Path, required=True)
    live_prepare.add_argument("--linux-config", type=Path, required=True)
    live_prepare.add_argument("--mmc-module", type=Path, required=True)
    live_prepare.add_argument("--output-dir", type=Path, required=True)
    live_prepare.add_argument("--mount-root", type=Path, required=True)
    live_prepare.add_argument("--media-preflight", type=Path, required=True)
    live_prepare.add_argument("--confirm-physical-device", required=True)
    live_prepare.add_argument("--clang", type=Path)
    live_prepare.add_argument("--lld", type=Path)
    live_prepare.add_argument("--mksquashfs", type=Path)
    live_prepare.add_argument("--unsquashfs", type=Path)
    live_prepare.set_defaults(handler=live_prepare_handler)

    live_authorize = stock_commands.add_parser("live-authorize")
    _add_common(live_authorize, inherited=True)
    live_authorize.add_argument("--recovery-dir", type=Path, required=True)
    live_authorize.add_argument(
        "--preserved-readback-dir", type=Path, required=True
    )
    live_authorize.add_argument("--restore-output-dir", type=Path, required=True)
    live_authorize.add_argument("--linux-config", type=Path, required=True)
    live_authorize.add_argument("--input-dir", type=Path, required=True)
    live_authorize.add_argument("--mount-root", type=Path, required=True)
    live_authorize.add_argument("--media-preflight", type=Path, required=True)
    live_authorize.add_argument("--confirm-physical-device", required=True)
    live_authorize.add_argument("--confirm-live-restore", required=True)
    live_authorize.set_defaults(handler=live_authorize_handler)

    live_restore = stock_commands.add_parser("live-restore")
    _add_common(live_restore, inherited=True)
    live_restore.add_argument("--recovery-dir", type=Path, required=True)
    live_restore.add_argument(
        "--preserved-readback-dir", type=Path, required=True
    )
    live_restore.add_argument("--restore-output-dir", type=Path, required=True)
    live_restore.add_argument("--linux-config", type=Path, required=True)
    live_restore.add_argument("--input-dir", type=Path, required=True)
    live_restore.add_argument("--serial-device", required=True)
    live_restore.add_argument("--confirm-serial-device", required=True)
    live_restore.set_defaults(handler=live_restore_handler)

    live_passivate = stock_commands.add_parser("live-passivate")
    _add_common(live_passivate, inherited=True)
    live_passivate.add_argument("--recovery-dir", type=Path, required=True)
    live_passivate.add_argument(
        "--preserved-readback-dir", type=Path, required=True
    )
    live_passivate.add_argument(
        "--restore-output-dir", type=Path, required=True
    )
    live_passivate.add_argument("--linux-config", type=Path, required=True)
    live_passivate.add_argument("--input-dir", type=Path, required=True)
    live_passivate.add_argument("--mount-root", type=Path, required=True)
    live_passivate.add_argument("--media-preflight", type=Path, required=True)
    live_passivate.add_argument("--confirm-physical-device", required=True)
    live_passivate.set_defaults(handler=live_passivate_handler)

    sd_prepare = stock_commands.add_parser("sd-prepare")
    _add_common(sd_prepare, inherited=True)
    sd_prepare.add_argument("--recovery-dir", type=Path, required=True)
    sd_prepare.add_argument("--preserved-readback-dir", type=Path, required=True)
    sd_source = sd_prepare.add_mutually_exclusive_group(required=True)
    sd_source.add_argument("--restore-output-dir", type=Path)
    sd_source.add_argument("--functional-stock-selection", type=Path)
    sd_prepare.add_argument("--kernel", type=Path, required=True)
    sd_prepare.add_argument("--linux-config", type=Path, required=True)
    sd_prepare.add_argument("--mmc-module", type=Path, required=True)
    sd_prepare.add_argument("--output-dir", type=Path, required=True)
    sd_prepare.add_argument("--mount-root", type=Path, required=True)
    sd_prepare.add_argument("--media-preflight", type=Path, required=True)
    sd_prepare.add_argument("--confirm-physical-device", required=True)
    sd_prepare.add_argument("--clang", type=Path)
    sd_prepare.add_argument("--lld", type=Path)
    sd_prepare.add_argument("--mksquashfs", type=Path)
    sd_prepare.add_argument("--unsquashfs", type=Path)
    sd_prepare.set_defaults(handler=sd_prepare_handler)

    sd_confirmation = stock_commands.add_parser("sd-confirmation")
    _add_common(sd_confirmation, inherited=True)
    sd_confirmation.add_argument(
        "--phase", choices=("authorize", "handoff", "retry"), default="authorize"
    )
    sd_confirmation.add_argument("--mount-root", type=Path, required=True)
    sd_confirmation.add_argument("--media-preflight", type=Path, required=True)
    sd_confirmation.set_defaults(handler=sd_confirmation_handler)

    sd_authorize = stock_commands.add_parser("sd-authorize")
    sd_handoff = stock_commands.add_parser("sd-handoff")
    sd_retry = stock_commands.add_parser("sd-retry")
    sd_passivate = stock_commands.add_parser("sd-passivate")
    for sd_command in (sd_authorize, sd_handoff, sd_retry, sd_passivate):
        _add_common(sd_command, inherited=True)
        sd_command.add_argument("--recovery-dir", type=Path, required=True)
        sd_command.add_argument(
            "--preserved-readback-dir", type=Path, required=True
        )
        sd_source = sd_command.add_mutually_exclusive_group(required=True)
        sd_source.add_argument("--restore-output-dir", type=Path)
        sd_source.add_argument("--functional-stock-selection", type=Path)
        sd_command.add_argument("--linux-config", type=Path, required=True)
        sd_command.add_argument("--input-dir", type=Path, required=True)
        sd_command.add_argument("--mount-root", type=Path, required=True)
        sd_command.add_argument("--media-preflight", type=Path, required=True)
        sd_command.add_argument("--confirm-physical-device", required=True)
    sd_authorize.add_argument("--confirm-live-restore", required=True)
    sd_authorize.set_defaults(handler=sd_authorize_handler)
    sd_handoff.add_argument("--confirm-stock-uboot-handoff", required=True)
    sd_handoff.set_defaults(handler=sd_handoff_handler)
    sd_retry.add_argument("--confirm-live-restore-retry", required=True)
    sd_retry.set_defaults(handler=sd_retry_handler)
    sd_passivate.set_defaults(handler=sd_passivate_handler)
